set(SRC_FILES
    App.cpp
    MenuScene.cpp
    GameObjectEx.cpp
    GameButton.cpp
    AnimatedGameObject.cpp
    EquipScene.cpp
    Utility.cpp
    CatBase.cpp
    BattleScene.cpp
    Entity.cpp
    Cat.cpp
    Enemy.cpp
    Timer.cpp
    UpgradeScene.cpp
    Stage.cpp
    Wallet.cpp
    DeployButton.cpp
    NumberSystem.cpp
    Camera.cpp
    EquipList.cpp
    BattleBackground.cpp
    CatList.cpp
    Workholic.cpp
    StageSelectScene.cpp
    LoadingRectangle.cpp
)

set(INCLUDE_FILES
    App.hpp
    Scene.hpp
    MenuScene.hpp
    GameObjectEx.hpp
    GameButton.hpp
    AnimatedGameObject.hpp
    EquipScene.hpp
    Utility.hpp
    CatBase.hpp
    EntityStats.hpp
    Enemy.hpp
    Cat.hpp
    BattleScene.hpp
    Entity.hpp
    Timer.hpp
    DebugUtil/BattleLog.hpp
    FrameScene.hpp
    UpgradeScene.hpp
    Stage.hpp
    Draggable.hpp
    EquipList.hpp
    Wallet.hpp
    DeployButton.hpp
    NumberSystem.hpp
    Camera.hpp
    CatList.hpp
    Sound.hpp
    BattleBackground.hpp
    Workholic.hpp
    StageSelectScene.hpp
    LoadingRectangle.hpp
)

set(TEST_FILES
)
