set(SRC_FILES
    App.cpp
    MenuScene.cpp
    GameObjectEx.cpp
    GameButton.cpp
    AnimatedGameObject.cpp
    Utility.cpp
    CatBase.cpp
    BattleScene.cpp
    Entity.cpp
    Cat.cpp
    Enemy.cpp
    Timer.cpp
    UpgradeScene.cpp
)

set(INCLUDE_FILES
    App.hpp
    Scene.hpp
    MenuScene.hpp
    GameObjectEx.hpp
    GameButton.hpp
    AnimatedGameObject.hpp
    Utility.hpp
    CatBase.hpp
    EntityStats.hpp
    Enemy.hpp
    Cat.hpp
    BattleScene.hpp
    Entity.hpp
    Timer.hpp
    DebugUtil/BattleLog.hpp
    FrameScene.hpp
    UpgradeScene.hpp
)

set(TEST_FILES
)
